# 核心配置模块
from app.core.config import (
    BACKEND_DIR,
    SCRIPTS_DIR,
    PORT,
    ALLOWED_ORIGINS,
    API_TOKEN,
    SCRIPT_TIMEOUT,
    EXECUTOR_MAX_WORKERS,
    EXECUTOR_QUEUE_SIZE,
    EXECUTOR_QUEUE_WAIT_TIMEOUT,
    EXECUTOR_MAX_CONCURRENT_SCRIPTS,
    EXECUTOR_RESULT_TTL,
    LOG_LEVEL,
    LOG_DIR,
    LOG_FILE_ENABLED,
)
